/**
 * Plots Data using python scripts.
 *
 * Plots are generated by executing python scripts. Scripts are executed via the system() command. For os other than windows a different option may be required (not tested)
 * Scripts must be located within src/Plots and follow a specific format and imported into plotCentral.py
 * The same scripts are used to generate the plots present in the rtd documentation.
 * Plots are eighter displayed during execution or saved to the specified plotDirectory.
 *
 * @author Alarich Herzner
 * @version 0.1 15.05.2020
*/

#pragma once

#include <string>
#include <filesystem>
#include <vector>

class Plot {

	std::string dataDirectory = "/docs/pyplots/";
	std::string plotDirectory = "/Output/";
	std::string pythonFile = std::filesystem::current_path().string() + "/src/Plots/plotCentral.py";
	bool showPlot = false;

public:
    /**@brief Using this constructor will lead to plots beeing saved (and not shown)*/
	Plot();
    /**
    @brief Use this constructor to specify in- and output
    @param dataDirectory relative path of the .dat file(s)
    @param plotDirectory relative path of the images (directory must exist)
    @param showPlot if true the plot will be shown instead of beeing saved
    */
	Plot(std::string dataDirectory, std::string plotDirectory, bool showPlot);
    /**
    @brief calls the plot script with given \p function name.
    @param function the name of the python file (excluding .py)
    @param params additional parameters passed to the python function (in addition to dataPath and showPlot)
    */
	void plot(std::string function,std::vector<std::string>params);
};